name: xboard-dev

networks:
  app-network:

volumes:
  xboard-config:

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s

  mariadb:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xboard
      MYSQL_USER: xboard
      MYSQL_PASSWORD: xboard

  xboard:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mariadb
    ports:
      - "7001:7001"
    networks:
      - app-network
    volumes:
      - xboard-config:/www/config
      - ./:/www
